variables:
  GITLAB: 'https://gitlab.com/dharmiksa/loadstatic.git'

stages:
    - build
    - deploy

build:
  stage: build
  script:
    - echo ${GITLAB}
    # - nohup python3 manage.py runserver 0:9000 &
    - python3 manage.py runserver 0:9000 &
    - pkill -f runserver
    - pwd
    # - rsync -avuP "/home/gitlab-runner/builds/oxi-Bp7w/0/dharmiksa/loadstatic" ssh -t ubuntu@13.232.232.231:/home/ubuntu/
    # - ssh -i "mykey.pem" ubuntu@65.2.141.2 "mkdir demo123" 
    # - ssh ubuntu@65.2.141.2 -o stricthostkeychecking=no " cd loadstatic; git pull ${GITLAB}; python3 manage.py runserver 0:8000 &"

#SUccess
deploy:
  stage: deploy
  script:
    # - ssh ubuntu@65.2.141.2 -o stricthostkeychecking=no "pkill -f runserver"
    - ssh ubuntu@65.2.141.2 -o stricthostkeychecking=no "cd loadstatic; git pull ${GITLAB};"
    - ssh ubuntu@65.2.141.2 -o stricthostkeychecking=no "cd loadstatic; nohup python3 manage.py runserver 0:8000 &"

     

    #- rsync -avuP "/home/gitlab-runner/builds/oxi-Bp7w/0/dharmiksa/loadstatic" ssh -A ubuntu@13.232.232.231:/home/ubuntu/
    - echo "Done ";


