name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  # call-workflow-2-in-local-repo:
  #   uses: ./.github/workflows/cicd.yml

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Run Project
      run: |
        nohup python3 manage.py runserver 0:3000 &
        pkill -f runserver
        pwd

  # deploy:  
  #   runs-on: self-hosted
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Deploy Project
  #     run: |
  #       ssh -t ubuntu@3.111.157.110 <<-EOF
  #       if [ -d 'LoadStatic']
  #       then
  #         cd LoadStatic
  #         git pull
  #       else
  #         git clone 'https://github.com/DharmikSA/LoadStatic.git'
  #         cd LoadStatic
  #       fi
  #       nohup python3 manage.py runserver 0:8000 &
  #       EOF
        
    # - name: Run Testsss
    #   run: |
    #     python3 manage.py test
